name: Lint
on: [push, pull_request]
jobs:
  build:
    name: Add-on configuration
    runs-on: ubuntu-latest
    strategy:
       matrix:
         channel: [porcupine1, snowboy, assist_microphone]
    steps:
      - name: ⤵️ Check out code from GitHub
        uses: actions/checkout@v4
      - name: 🚀 Run Home Assistant Add-on Lint on ${{ matrix.channel }}
        uses: frenck/action-addon-linter@v2.1
        with:
          path: "./${{ matrix.channel }}"
